name: "Docker image build and push"

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image name"
        required: true
      version:
        description: "Docker image version"
        required: true

jobs:
  push-to-docker-hub:
    runs-on: ubuntu-latest
    name: Build and push Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build and push Docker image
        run: ./build.sh ${{github.event.inputs.version}}
        working-directory: ${{github.event.inputs.image}}